apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "my-notepad-chart.frontendFullname" . }}-nginx-config
  labels:
    {{- include "my-notepad-chart.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  nginx.conf: |
    server {
        listen 80;
        server_name _;
        
        location / {
            root /usr/share/nginx/html;
            index index.html index.htm;
            try_files $uri $uri/ /index.html;
        }
        
        location /api/ {
            proxy_pass http://{{ include "my-notepad-chart.backendFullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.backend.service.port }}/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
