apiVersion: v2
name: my-notepad-chart
description: A Helm chart for my Notepad application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgresql
    version: "13.2.24"
    repository: "https://charts.bitnami.com/bitnami"
    alias: database